### ISSUE TITLE
config.clj file missing?

### ISSUE THREAD

**Issue by huoww07** [jsa-aerial/aerobio#15]
Hi, I'm trying to see if I could install the package on my MacBook pro. It looks like the config.clj is missing? I wonder if you have it or it's not necessary for running? Thank you!

**Comment by jsa-aerial** [comment]
Let me ask a question: Do you have access to an Ubuntu Linux machine at Tufts?  This could be 14.04, 16.04 or 18.04.

**Comment by huoww07** [comment]
Yep, we do. I also have an ubuntu Linux myself. So i could try it out on my own machine first.

**Comment by jsa-aerial** [comment]
What version do you have?  I could put together a precompiled archive of binaries for the C/C++.

**Comment by huoww07** [comment]
I have ubuntu 16. The Tufts HPC cluster uses Redhat 7 (RHEL 7)

**Comment by jsa-aerial** [comment]
OK, that sounds interesting - what are the specs on the machine? I can put out the new uberjar and put an archive together of the binaries of various external tools.  I can put one of the python versions in there as well or maybe as another package (yes, there are two versions of python needed due to - I don't want to think about it).  You will still need R and some packages for that.  I am assuming your default python is 2.7.(5 or 6).

Redhat (and by extension Centos) won't work for this scheme.  You would need to rebuild all the external tools since RH made a hash of where it puts system libraries (true since primordial days).

**Comment by huoww07** [comment]
I have a lenovo thinkpad X220 from 2011, Intel Core i7, 4Gb RAM, 250Gb hard drive(i hope this is what you were asking about the specs, if not, here is a page with more info: https://support.lenovo.com/us/en/solutions/pd015812/). My Ubuntu was installed as duel system alongside my windows 7, so it has about 100Gb storage. My default is python 3 I think but I built anaconda environment for python 2.7.5 packages.

**Comment by jsa-aerial** [comment]
Well, in theory something could run on that, but in practice it likely would have several problems with OOM issues.  Also, that 250GB HD would probably not even hold a single run.   I would strongly suggest a machine with at least 32GB RAM, 1TB of disk and at least 8 cores.

**Comment by huoww07** [comment]
I see... we might not have that kind of set up in the lab right now, so it doesn't look like it can be set up. I think I'm getting an account for BC server, so maybe I will just wait and use your server instead. Sorry about the trouble

**Comment by jsa-aerial** [comment]
This is not trouble - it is really good information about things.  Let me ask another question - is the HPC cluster the only machines at Tufts that have these sort of resources that might be available to you (your lab)?  I'm guessing that setup is the typical queue management setup (Torque, PBS, OpenHPC, or some such) which needs environment modules and things.  Not sure how smoothly that would work.

**Comment by huoww07** [comment]
Yeah, HPC cluster is what we typically use. Our lab computer may have better memory/storage, but unfortunately it's Mac OS system. The HPC cluster uses slurm for queue management setup. Here are some pages that I don't quite understand which may have more information on the specs: 1. https://wikis.uit.tufts.edu/confluence/display/TuftsUITResearchComputing/Home and 2. https://it.tufts.edu/research-technology/high-performance-computing.

**Comment by jsa-aerial** [comment]
Yeah, that's yet-another-qm system.  They are all cut from the same cloth - more or less.  I will take a look at those links, but I am guessing now it will be miserable.

**Comment by huoww07** [comment]
There is no rush on this. It would be nice if we could have it set up here. Thank you so much for your help and explanations!

**Comment by jsa-aerial** [comment]
Any chance your lab may be able to obtain a machine in the range I gave? It is worth noting that something like that these days (with all SSD drives) is only about $2k  With regular old spinning rust drives, probably only $1500
